<a href="https://colab.research.google.com/github/shtrausslearning/sf_mldl/blob/main/numpy_recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy utils

In [ ]:
from functools import partial

In [ ]:
salary = [159.3, 563.7, 578.1, 248.3]

scale = 1.05
# salary_upd = [round(el * scale, 2) for el in salary]
salary_upd = [el * scale for el in salary]
# salary_upd_rounded = map(round, salary_upd)
salary_upd_rounded = list(map(lambda x: round(x, 2), salary_upd))
round_2 = partial(round, tol=2)
# salary_upd = salary * scale
print(salary)
print(salary_upd)
print(salary_upd_rounded)


[159.3, 563.7, 578.1, 248.3]
[167.26500000000001, 591.8850000000001, 607.005, 260.71500000000003]
[167.27, 591.89, 607.0, 260.72]


In [ ]:
import numpy as np

salary = [159.3 / 10000000, 563.7 / 10000000,
          578.1 / 10000000, 248.3 / 10000000] * 1

salary_as_np = np.array(salary)
# salary_as_np = np.fromiter(map(round, salary), dtype='float32')

print(type(salary_as_np))
# print(salary)
print(salary_as_np)

scale = 10000000.05
salary_upd = salary_as_np * scale
print(salary_upd)
print(np.round(salary_upd, 2))
print(list(np.round(salary_upd, 2)))



<class 'numpy.ndarray'>
[1.593e-05 5.637e-05 5.781e-05 2.483e-05]
[159.3000008  563.70000282 578.10000289 248.30000124]
[159.3 563.7 578.1 248.3]
[159.3, 563.7, 578.1, 248.3]


In [ ]:
# salary = [159.3, 563.7, 578.1, 248.3]
# salary = [-159, 563, 578, 248]
salary = [159, 563, 578, 248]

# salary_as_np = np.array(salary)
# salary_as_np = np.array(salary, dtype='uint32')
# salary_as_np = np.array(salary, dtype='float32')
salary_as_np = np.array(salary, dtype=np.float32)
print(salary_as_np)
print(salary_as_np.shape)
print(salary_as_np.itemsize)
print(salary_as_np.dtype)




[159. 563. 578. 248.]
(4,)
4
float32


In [ ]:
! pip install memory_profiler

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
from memory_profiler import profile

NUMS = 10 ** 6


@profile
def list_case():
    nums = [num for num in range(NUMS)]
    print(type(nums), len(nums), nums[-1])


@profile
def np_case():
    nums = np.arange(NUMS)
    print(type(nums), len(nums), nums[-1], nums.dtype)


list_case()
np_case()

# if __name__ == "__main__":
#   list_case()
#   np_case()

In [ ]:
salary = [579, 470, 193, 328, 478, 236, 697]
print(sorted(salary))
salary_as_np = np.array(salary)
print(salary_as_np.mean())
print(np.mean(salary_as_np))
print(np.median(salary_as_np))

percents = (1, 5, 10, 25, 50, 75, 95, 99)
# percents = (25, 50, 75)
salary_stat = np.percentile(salary_as_np, percents)
print(salary_stat)
print(dict(zip(percents, salary_stat)))


[193, 236, 328, 470, 478, 579, 697]
425.85714285714283
425.85714285714283
470.0
[195.58 205.9  218.8  282.   470.   528.5  661.6  689.92]
{1: 195.58, 5: 205.9, 10: 218.8, 25: 282.0, 50: 470.0, 75: 528.5, 95: 661.5999999999999, 99: 689.92}


In [ ]:
nums = np.array([1, 2, 3, 4])
nums_2 = np.array([5, 6, 7, 8])
nums_sum = nums + nums_2
nums_sub = nums - nums_2
nums_mul = nums * nums_2
print(nums_sum)
print(nums_sub)
print(nums_mul)

nums_3 = np.append(nums, [9, 10])
print(nums_3)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 1  2  3  4  9 10]


In [ ]:
nums = np.arange(1, 51)
# print(nums, nums.shape)
# prices = [1, 2, 3]
# print(prices[2:None])

# new_shape = (5, -1)
# nums_by_strict = nums.reshape(new_shape)
# print(nums_by_strict, nums_by_strict.shape)

# nums_by_ten = nums.reshape((-1, 10))
# nums_by_ten = nums.reshape((10, -1))
# print(nums_by_ten)
# print(nums_by_ten.sum())
# print(nums_by_ten.sum(axis=0))
# print(nums_by_ten.sum(axis=1))
# print(nums_by_ten.prod(axis=0))
# print(nums_by_ten.prod(axis=1))

nums_3d = nums.reshape((-1, 5, 2))
print(nums_3d)
print(nums_3d.shape)
print(nums_3d[0, 0, 0])
print(nums_3d[:, 0, 0])
print(nums_3d[:, :, 0])



In [ ]:
nums = np.arange(1, 101, dtype=np.int32)

nums_by_ten = nums.reshape((-1, 10))
print(nums_by_ten)
print(np.linalg.det(nums_by_ten))
nums_by_ten_t = nums_by_ten.transpose()
print(nums_by_ten_t)


In [ ]:
nums = np.arange(1, 21)
nums_by_ten = nums.reshape((-1, 2, 10))
print(nums_by_ten)
nums_flat = nums_by_ten.reshape(-1)
print(nums_flat)
nums = np.arange(1, 10.4736842, 0.47368421)
print(len(nums), nums)
#
nums_2 = np.linspace(1, 10, 9)
print(len(nums_2), nums_2)


def my_f(x, y):
    # print(x.dtype)
    return x ** 2 + y + 1


# x = np.linspace(1, 10, 10)
# y = np.linspace(1, 5, 10)
z = np.fromfunction(my_f, (10, 5))
print(my_f(9, 4))
print(z)

# e_arr = np.empty((4, 5))
# e_arr = np.empty((4, 5), dtype=np.uint16)
e_arr = np.zeros((4, 5), dtype=np.uint16)
print(e_arr, e_arr.dtype)


[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20 [1.         1.47368421 1.94736842 2.42105263 2.89473684 3.36842105
 3.84210526 4.31578947 4.78947368 5.26315789 5.7368421  6.21052631
 6.68421052 7.15789473 7.63157894 8.10526315 8.57894736 9.05263157
 9.52631578 9.99999999]
9 [ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
86
[[ 1.  2.  3.  4.  5.]
 [ 2.  3.  4.  5.  6.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [17. 18. 19. 20. 21.]
 [26. 27. 28. 29. 30.]
 [37. 38. 39. 40. 41.]
 [50. 51. 52. 53. 54.]
 [65. 66. 67. 68. 69.]
 [82. 83. 84. 85. 86.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] uint16


In [ ]:
nums = np.arange(1, 21)
print(nums)
# lighten = np.where(pict[0, :, :] > 250)
idx_1 = nums > 10
print(idx_1, type(idx_1), idx_1.dtype)
nums_1 = nums[idx_1]
print(nums_1)
print(nums[nums > 10])
print(nums[nums ** 2 > 10])
print(nums.cumsum())
print(np.diff(nums))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True] <class 'numpy.ndarray'> bool
[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
